-- Esquema de hechos XBRL CMF. El ETL escribe con service_role; la lectura pública
-- se limita a hechos normalizados y documentos, nunca a credenciales de origen.
create table if not exists public.issuer (
  id bigint generated by default as identity primary key,
  rut text not null unique,
  name text not null,
  status text not null default 'Vigente',
  source text not null default 'CMF',
  retrieved_at timestamptz not null default now()
);

create table if not exists public.quarter (
  id bigint generated by default as identity primary key,
  period_code text not null unique,
  period_end date not null,
  fiscal_year integer not null,
  fiscal_month integer not null
);

create table if not exists public.source_document (
  id bigint generated by default as identity primary key,
  issuer_rut text not null references public.issuer(rut),
  period_code text not null references public.quarter(period_code),
  statement_type text not null check (statement_type in ('C', 'I')),
  page_url text not null,
  source_url text not null,
  content_hash text not null,
  local_path text,
  retrieved_at timestamptz not null,
  unique (issuer_rut, period_code, statement_type)
);

create table if not exists public.xbrl_fact (
  id bigint generated by default as identity primary key,
  source_document_id bigint not null references public.source_document(id) on delete cascade,
  issuer_rut text not null references public.issuer(rut),
  statement_type text not null check (statement_type in ('C', 'I')),
  concept text not null,
  context_id text not null,
  period_start date,
  period_end date,
  instant date,
  unit text,
  decimals text,
  value_numeric numeric,
  value_text text,
  dimensions jsonb not null default '{}'::jsonb,
  source_url text not null,
  unique (source_document_id, context_id, concept, dimensions)
);

create index if not exists idx_xbrl_fact_issuer_period on public.xbrl_fact (issuer_rut, period_end);
create index if not exists idx_xbrl_fact_concept on public.xbrl_fact (concept);
create index if not exists idx_source_document_hash on public.source_document (content_hash);

alter table public.issuer enable row level security;
alter table public.quarter enable row level security;
alter table public.source_document enable row level security;
alter table public.xbrl_fact enable row level security;

create policy "public can read issuer catalog" on public.issuer for select to anon, authenticated using (true);
create policy "public can read quarters" on public.quarter for select to anon, authenticated using (true);
create policy "public can read source lineage" on public.source_document for select to anon, authenticated using (true);
create policy "public can read normalized facts" on public.xbrl_fact for select to anon, authenticated using (true);

