-- Modo gratuito: PostgreSQL conserva el catalogo y la trazabilidad, pero no
-- almacena los millones de hechos XBRL. El read model compacto se publica con
-- el frontend a partir del SQLite local generado por el ETL.
drop table if exists public.xbrl_fact;

create table public.xbrl_fact (
  id bigint generated by default as identity primary key,
  source_document_id bigint not null references public.source_document(id) on delete cascade,
  issuer_rut text not null references public.issuer(rut),
  statement_type text not null check (statement_type in ('C', 'I')),
  concept text not null,
  context_id text not null,
  period_start date,
  period_end date,
  instant date,
  unit text,
  decimals text,
  value_numeric numeric,
  value_text text,
  dimensions jsonb not null default '{}'::jsonb,
  source_url text not null
);

create index idx_xbrl_fact_issuer_period on public.xbrl_fact (issuer_rut, period_end);
alter table public.xbrl_fact enable row level security;
create policy "public can read normalized facts" on public.xbrl_fact
  for select to anon, authenticated using (true);
